import { homedir } from 'node:os'
import { nodeBinDir, resolveDshBin, resolveDshHome, resolveNode } from './paths.js'

/** systemd ExecStart argument quoting: wrap in double quotes, escape \ and ". */
function quote(arg) {
  return `"${String(arg).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/**
 * Render the dsh-daemon.service unit text. `host`/`port` are optional; when
 * omitted the unit runs a bare `dsh web`, which keeps dsh's own defaults
 * (127.0.0.1:3080). `cwd` must already be resolved.
 */
export function buildUnit({ host, port, cwd }) {
  const node = resolveNode()
  const bin = resolveDshBin()
  const dshHome = resolveDshHome()
  const home = homedir()
  const workDir = cwd ?? home

  const args = ['web']
  if (host) args.push('--host', host)
  if (port) args.push('--port', String(port))
  const execStart = [quote(node), quote(bin), ...args.map(quote)].join(' ')

  const path = [nodeBinDir(), '/usr/local/bin', '/usr/bin', '/bin'].join(':')

  return `# Generated by dsh-daemon. Reinstall to regenerate:
#   dsh --profile daemon install [--host H] [--port P] [--cwd DIR]
[Unit]
Description=dsh web daemon (DeepSeek Harness browser UI)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${execStart}
WorkingDirectory=${workDir}
Environment=DSH_HOME=${dshHome}
Environment=HOME=${home}
Environment=PATH=${path}
Restart=on-failure
RestartSec=2
TimeoutStopSec=30

[Install]
WantedBy=default.target
`
}
