import { homedir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { nodeBinDir, resolveDshBin, resolveDshHome, resolveNode } from './paths.js'

/** systemd ExecStart argument quoting: wrap in double quotes, escape \ and ". */
function quote(arg) {
  return `"${String(arg).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/** Absolute path of this package's graceful restart helper. */
function gracefulHelperPath() {
  return fileURLToPath(new URL('./graceful.js', import.meta.url))
}

/**
 * Render the dsh-daemon.service unit text. `host`/`port` are optional; when
 * omitted the unit runs a bare `dsh web`, which keeps dsh's own defaults
 * (127.0.0.1:3080). `cwd` must already be resolved.
 */
export function buildUnit({ host, port, cwd, trustedHosts = [], resumePrompt }) {
  const node = resolveNode()
  const bin = resolveDshBin()
  const dshHome = resolveDshHome()
  const home = homedir()
  const workDir = cwd ?? home
  const helper = gracefulHelperPath()
  const stateFile = join(dshHome, 'daemon-resume.json')
  const boundHost = host ?? '127.0.0.1'
  const boundPort = String(port ?? 3080)

  const args = ['web']
  if (host) args.push('--host', host)
  if (port) args.push('--port', String(port))
  for (const authority of trustedHosts) args.push('--trusted-host', authority)
  const execStart = [quote(node), quote(bin), ...args.map(quote)].join(' ')

  const gracefulArgs = ['--phase', 'before-stop', '--host', boundHost, '--port', boundPort, '--state', stateFile]
  const execStop = [quote(node), quote(helper), ...gracefulArgs.map(quote)].join(' ')
  const resumeArgs = ['--phase', 'after-start', '--host', boundHost, '--port', boundPort, '--state', stateFile]
  if (resumePrompt !== undefined && resumePrompt !== '') resumeArgs.push('--resume-prompt', resumePrompt)
  const execStartPost = [quote(node), quote(helper), ...resumeArgs.map(quote)].join(' ')

  const path = [nodeBinDir(), '/usr/local/bin', '/usr/bin', '/bin'].join(':')

  return `# Generated by dsh-daemon. Reinstall to regenerate:
#   dsh --profile daemon install [--host H] [--port P] [--cwd DIR] [--resume-prompt TEXT]
[Unit]
Description=dsh web daemon (DeepSeek Harness browser UI)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${execStart}
ExecStartPost=-${execStartPost}
ExecStop=-${execStop}
WorkingDirectory=${workDir}
Environment=DSH_HOME=${dshHome}
Environment=HOME=${home}
Environment=PATH=${path}
Restart=on-failure
RestartSec=2
TimeoutStopSec=60

[Install]
WantedBy=default.target
`
}
